name: 'Linter'
on: [push]

jobs:
  eslintRun:
    runs-on: ubuntu-latest
    name: 'Eslint'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i eslint
      - run: npm run lint